import { PollQuestion, AudienceHotTake } from './types';

export const INITIAL_POLLS: PollQuestion[] = [
  {
    id: 'poll-envelope-1',
    category: 'hideaway',
    categoryLabel: '💌 THE RED ENVELOPE MATCH',
    title: "Who Should Win Tonight's Grand Candlelit Date Night?",
    prompt: "Tonight at 'Jab We Matched', 500 spectators decide which newly paired couple unseals the Red Envelope to win the VIP romantic dinner table and roses!",
    requiresVoterInput: true,
    inputPromptText: 'Spectator Hot Take Required: Why does this couple belong together?',
    allowAudienceOptions: true,
    status: 'active',
    totalVotes: 284,
    winnerOptionId: undefined,
    createdAt: new Date().toISOString(),
    options: [
      {
        id: 'opt-env-1',
        label: 'Kabir & Ananya',
        description: 'The childhood best friends turned slow-burn romantic match. Sparks flying all evening!',
        avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        votes: 146,
        tag: 'Slow Burn Romance 💕',
      },
      {
        id: 'opt-env-2',
        label: 'Rohan & Priya',
        description: 'Enemies-to-lovers dynamic with electric stage banter. Unpredictable and high voltage!',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        votes: 89,
        tag: 'Spicy Chemistry 🔥',
      },
      {
        id: 'opt-env-3',
        label: 'Aarav & Meera',
        description: 'The speed-dating blind match that instantly bonded over Bollywood tunes and cutting chai.',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        votes: 38,
        tag: 'Fan Favorite Duo 🌸',
      },
      {
        id: 'opt-env-4',
        label: 'Audience Write-In: Nominate a New Pair!',
        description: 'Think two people on stage secretly belong together? Nominate your own dream match.',
        avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
        votes: 11,
        requiresWriteIn: true,
        tag: 'Audience Matchmaker ✍️',
      },
    ],
  },
  {
    id: 'poll-redflag-2',
    category: 'drama',
    categoryLabel: '🚩 RED FLAG OR BOLLYWOOD ROMANCE?',
    title: "He texted 'Tum bohot alag ho' at 2 AM with a 7-minute audio. Red flag or pure romance?",
    prompt: "The hosts intercepted his late-night speed-dating notes. Spectators in the hall, what is your official verdict on his intentions?",
    requiresVoterInput: true,
    inputPromptText: 'Tribunal Verdict Required: State your case on whether he is genuine or toxic:',
    allowAudienceOptions: true,
    status: 'active',
    totalVotes: 342,
    winnerOptionId: undefined,
    createdAt: new Date().toISOString(),
    options: [
      {
        id: 'opt-rf1',
        label: 'Major Red Flag 🚩 Block Him Immediately!',
        description: "That is textbook sweet-talker energy. He definitely forwarded that 7-minute audio to 4 other girls.",
        votes: 198,
        tag: 'Red Flag Alert 🚩',
      },
      {
        id: 'opt-rf2',
        label: "Pure Aditya Kashyap Energy 🥺 He's Just a Hopeless Romantic",
        description: 'He was being vulnerable and sincere! True love starts with unhinged late-night voice messages.',
        votes: 104,
        tag: 'Hopeless Romantic 💖',
      },
      {
        id: 'opt-rf3',
        label: "Playing for the Stage Cameras 🎭 It's All for the Plot",
        description: 'He rehearsed that speech in the mirror before coming to Jab We Matched tonight.',
        votes: 31,
        tag: 'Bollywood Melodrama 🎬',
      },
      {
        id: 'opt-rf4',
        label: 'Audience Write-In: Prescribe His Stage Penalty!',
        description: 'Should he sing Tum Se Hi on stage or buy samosas for the entire front row?',
        votes: 9,
        requiresWriteIn: true,
        tag: 'Custom Penalty ⚡',
      },
    ],
  },
  {
    id: 'poll-compatibility-3',
    category: 'truth_or_dare',
    categoryLabel: '💘 THE SOULMATE COMPATIBILITY TEST',
    title: 'Which Matched Couple Has Genuine Staying Power After Tonight?',
    prompt: 'Beyond the lights of the auditorium, which couple will actually last beyond the upcoming weekend?',
    requiresVoterInput: true,
    inputPromptText: 'Your Reality Check: What will make or break their connection?',
    allowAudienceOptions: false,
    status: 'active',
    totalVotes: 215,
    winnerOptionId: undefined,
    createdAt: new Date().toISOString(),
    options: [
      {
        id: 'opt-ct1',
        label: 'Dev & Tara (Pure Soulmate Harmony)',
        description: 'Same dry humor, shared Spotify playlist, already planning date #2.',
        votes: 119,
        tag: 'Soulmate Chemistry 💍',
      },
      {
        id: 'opt-ct2',
        label: 'Zayn & Natasha (Chaotic Opposites)',
        description: 'Electric sparks and endless bickering. High passion but will they text back tomorrow?',
        votes: 72,
        tag: 'Rollercoaster Romance 🎢',
      },
      {
        id: 'opt-ct3',
        label: 'Neither 🙅 Destination: Friendzone',
        description: 'They will follow each other on Instagram tonight and never talk again.',
        votes: 24,
        tag: 'Campus Reality 💀',
      },
    ],
  },
  {
    id: 'poll-wildcard-4',
    category: 'recoupling',
    categoryLabel: '⚡ THE WILDCARD MATCHMAKER BUTTON',
    title: 'Should The Mystery Audience Member Challenge The Stage Match?',
    prompt: 'Someone in row 4 has declared they have an unresolved confession for one of the stage contestants! Do the 500 spectators give them the microphone?',
    requiresVoterInput: true,
    inputPromptText: 'Why vote this way? Share your reaction with the host:',
    allowAudienceOptions: true,
    status: 'active',
    totalVotes: 188,
    winnerOptionId: undefined,
    createdAt: new Date().toISOString(),
    options: [
      {
        id: 'opt-wc1',
        label: 'Give Them The Mic! 🎤 We Need Peak Bollywood Drama',
        description: 'We did not come to Jab We Matched for peace, we came for jaw-dropping plot twists!',
        votes: 134,
        tag: 'Peak Cinema 🍿',
      },
      {
        id: 'opt-wc2',
        label: 'Protect The Couple 🛡️ Respect Their Match',
        description: 'They just had a sweet moment together; do not derail the connection with outside chaos.',
        votes: 54,
        tag: 'Protect The Match 🕊️',
      },
    ],
  },
];

export const INITIAL_HOT_TAKES: AudienceHotTake[] = [
  {
    id: 'ht-1',
    pollId: 'poll-envelope-1',
    voterName: 'PoojaFromRow3',
    optionLabel: 'Kabir & Ananya',
    hotTake: 'Kabir literally smiled like Aditya in Jab We Met when Ananya walked on stage. If they do not win the red envelope date I will personally protest!',
    spiceLevel: 5,
    timestamp: 'Just now',
  },
  {
    id: 'ht-2',
    pollId: 'poll-redflag-2',
    voterName: 'BollyGeek99',
    optionLabel: 'Major Red Flag 🚩 Block Him Immediately!',
    hotTake: 'A 7-minute voice note at 2 AM is not romantic, that is a whole podcast episode. Block him and save yourself!',
    spiceLevel: 5,
    timestamp: '1 min ago',
  },
  {
    id: 'ht-3',
    pollId: 'poll-envelope-1',
    voterName: 'ChaiLoverRohan',
    optionLabel: 'Rohan & Priya',
    hotTake: 'Rohan and Priya have that exact enemies-to-lovers tension that makes for top tier reality TV. Send them to the candlelit table!',
    spiceLevel: 4,
    timestamp: '3 mins ago',
  },
];
